[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "torch>=2.14.1",
    "transformers>=5.19.0",
]
